import ReactToastProvider from "@/providers/ReactToastProvider";
import "./globals.css";
import type { Metadata } from "next";
import ReduxProvider from "@/providers/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactToastProvider>
          <ReduxProvider>{children}</ReduxProvider>
        </ReactToastProvider>
      </body>
    </html>
  );
}
