export enum PAYOUT_TYPE_ENUM {
    SECURITY_AMOUNT = "SECURITY_FEE",
    ORDER_AMOUNT = "ORDER_AMOUNT"
}

export enum PAYOUT_PAYMENT_STATUS_ENUM {
    PAID = "PAID",
    REJECTED = "REJECTED",
    PENDING = "PENDING"
}